### PR TITLE
Rebuild for protobuf 3.12.3

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Build currently fail because of 
```
$PREFIX/include/gazebo-11/gazebo/msgs/cessna.pb.h:56:51: error: no type named 'AuxillaryParseTableField' in namespace 'google::protobuf::internal'; did you mean 'AuxiliaryParseTableField'?
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
```
Which was renamed in protobuf 3.12.3. Last build had protobuf 3.12.1

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Any idea why this fails on Linux? Error:
```
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libGL.so: undefined reference to `XML_SetUserData'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libGL.so: undefined reference to `XML_Parse'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libGL.so: undefined reference to `XML_ParseBuffer'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libGL.so: undefined reference to `XML_ErrorString'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libGL.so: undefined reference to `XML_GetCurrentColumnNumber'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libGL.so: undefined reference to `XML_ParserFree'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libGL.so: undefined reference to `XML_ParserCreate'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libGL.so: undefined reference to `XML_GetErrorCode'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libGL.so: undefined reference to `XML_GetCurrentLineNumber'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libGL.so: undefined reference to `XML_SetElementHandler'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libGL.so: undefined reference to `XML_GetBuffer'
```

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please restart ci

**Comment by wolfv** [comment]
very weird. looks like these symbols come from libexpat?

**Comment by wolfv** [comment]
https://anaconda.org/conda-forge/expat/

**Comment by Tobias-Fischer** [comment]
Yes that's right. `expat` is actually pulled in the builds as dependency already. So I am not sure why the linux build fails. It hasn't recently been updated either. And it's very odd that the linker fails on libGL.

I'll leave it at that, maybe someone with more conda experience has an idea. I wonder whether this error occurs in other repos.

**Comment by wolfv** [comment]
awesome @Tobias-Fischer !

**Pull request merged**
