### PR TITLE
Add compatibility check for osx deployment target

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Review by traversaro — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Seems like we would need to pin TBB on Windows to 2020.1 to get it compiled there (https://stackoverflow.com/questions/64510477/error-c2061-syntax-error-identifier-concurrent-vectortemplate-type-paramet) - but seeing that nothing changed on Win, I suggest to merge this PR anyhow so the changes land in OSX?

**Comment by Tobias-Fischer** [comment]
The windows build now fails because protobuf in the downstream packages is newer than here - so we need #47. I suggest to merge this PR first, then increase the build number in #47 (and resolve any possible conflicts). So it's ready to be merged @wolfv @seanyen

**Comment by traversaro** [comment]
> 
> 
> The windows build now fails because protobuf in the downstream packages is newer than here - so we need #47. I suggest to merge this PR first, then increase the build number in #47 (and resolve any possible conflicts). So it's ready to be merged @wolfv @seanyen

Downstream use of Gazebo without any pin is effectively broken on Windows given this situation (see conda/Windows failures in https://github.com/robotology/robotology-superbuild/actions/runs/502722666) so I think we can go on and merge, I don't think @wolfv will be angry. : )

**Pull request merged**
