### PR TITLE
Activate scripts for gazebo 9

### LINKED ISSUE #34: We have to set GAZEBO_RESOURCE_PATH for gazebo 9
Gazebo starts when I do:

export GAZEBO_RESOURCE_PATH=/home/wolfv/miniconda3/envs/ros/share/gazebo-9

but fails (with logs using `--verbose`)

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fix #34

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@wolfv this is untested, but should fix #40. It's copied 1:1 from the gazebo11 (i.e. master) branch. Do you think this needs further work to work properly?

**Comment by Tobias-Fischer** [comment]
On a different note, I'm not even sure whether it's worth maintaining gazebo9 anymore, as we use gazebo11 for ros-noetic. But if we want to have ros-melodic, we should take care of this.

**Comment by Tobias-Fischer** [comment]
This is ready to be merged @seanyen

**Comment by wolfv** [comment]
Awesome!

**Pull request merged**
