### PR TITLE
Bump build number, prepare to libprotobuf 3.20 and switch to vs2019

### PR DESCRIPTION
**Pull request by traversaro**
Debug the reason why the libprotobuf320 migration is failing.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Ok, the problem seems to be that we do not have a ffmpeg 4.4 build, see https://github.com/conda-forge/gazebo-feedstock/pull/126 .

**Comment by Tobias-Fischer** [comment]
Needs https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/64

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Sounds good

**Pull request merged**
