### PR TITLE
Also add build against qt 5.15 (qt-main package)

### PR DESCRIPTION
**Pull request by traversaro**
This also adds a qt 5.15-based build, while continuing to build the usual 5.12 build. This is done for two reasons:
* This is a form of mitigation for https://github.com/conda-forge/gazebo-feedstock/issues/119 (hoping that qt5.15 are not affected by this problem). 
* This will permit to build macOS arm64 binaries.

Once conda-forge pinning move to qt 5.15, we can remove this logic. The build matrix is doubling due to this, but I hope that conda-forge will move soon enough to qt 5.15 to ensure that this is not a problem in the long term.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
CI jobs are failing due to the fact that binaries created by  https://github.com/conda-forge/qwt-feedstock/pull/30 .

**Comment by Tobias-Fischer** [comment]
Nice! Do you want to do the osx-arm64 migration separately?

**Comment by traversaro** [comment]
> Nice! Do you want to do the osx-arm64 migration separately?

Yes, unfortunatly the cross-compilation support will need some non-trivial changes.

**Review by Tobias-Fischer — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
I'm happy to merge unless there are objections @conda-forge/gazebo

**Comment by traversaro** [comment]
> I'm happy to merge unless there are objections @conda-forge/gazebo

Thanks! I was waiting for the CI to be happy, merged now.

**Pull request merged**
