### PR TITLE
Add bzip and zlib for all platforms

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Latest Azure build failed for linux and win

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @traversaro @wolfv - any idea what's going on here? All was fine in #115 (GitHub actions) but Azure failed and now GA fails here, too.

**Comment by Tobias-Fischer** [comment]
It's because of https://github.com/conda-forge/boost-cpp-feedstock/pull/115

**Comment by benmwebb** [comment]
> It's because of [conda-forge/boost-cpp-feedstock#115](https://github.com/conda-forge/boost-cpp-feedstock/pull/115)

I think you mean conda-forge/boost-cpp-feedstock#114 (all of my CI is failing due to this breakage too), but yes, the PR you reference should fix that once it's merged.

**Comment by Tobias-Fischer** [comment]
Yes correct i mean https://github.com/conda-forge/boost-cpp-feedstock/issues/114 :)

**Comment by Tobias-Fischer** [comment]
Hi @wolfv @ traversaro - so I guess we don't need this PR, and should simply trigger a rerun of the Azure builds in a few hours, after https://github.com/conda-forge/boost-cpp-feedstock/pull/115 will be merged and the CDN updated?

**Comment by Tobias-Fischer** [comment]
Triggered rebuild, closing here

**Pull request closed without merging**
