### PR TITLE
Fix usage of Gazebo plugins as linked libraries on macOS

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Should we use a glob instead? Anything with plugin in the name?

**Comment by traversaro** [comment]
> Should we use a glob instead? Anything with plugin in the name?

I think more and less everything in the `$PREFIX/lib/gazebo-11/plugins` folder has plugin in its name, so we could just iterate on the directory content. However, to reduce the chance of clobbering I would just keep that list, that is the one we actually need for gazebo-ros-plugins.

**Comment by Tobias-Fischer** [comment]
Great, thanks for the explanation!

**Pull request merged**
