### PR TITLE
Build against both ogre 1.12 and 1.10

### PR DESCRIPTION
**Pull request by traversaro**
This will probably be necessary in any case to install gazebo in a ros2 environement with rviz2 installed. However, my main interest right now is to debug the ogre 1.12 build of conda-forge (for https://github.com/RoboStack/ros-galactic/issues/24), as I already had experience in using Gazebo with Ogre 1.12 built via vcpkg, so it is more familiar for me to debug any problem here. 

I tried to use `track_features` to de-prioritize ogre 1.12, but I am not sure if this actually works, but I gave it a shot.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
I suspect all the failure are unrelated to the actual PR and related to https://github.com/conda-forge/qwt-feedstock/pull/28 . Let's try with a clean build.

**Review by Tobias-Fischer — APPROVED** [review]

**Comment by traversaro** [comment]
The `track_features` aspect seems to work, if I install `conda create -n gazebo gazebo` or `mamba create -n gazebo gazebo` I get the ogre 1.10 version, but with `conda create -n gazebo gazebo ogre=1.12` or `mamba create -n gazebo gazebo ogre 1.12` I get the ogre 1.12 version.

**Pull request merged**
