### PR TITLE
Fix shader patch

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I mistakenly merged in #91 although the build failed. This PR fixes it.

**Comment by Tobias-Fischer** [comment]
Patch now applies cleanly. This time I'll leave it up to you to merge it in @traversaro @wolfv :)

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @Tobias-Fischer !

**Comment by traversaro** [comment]
By the way I just noticed that  Gazebo 11.8.1 was released (see https://github.com/osrf/gazebo/releases/tag/gazebo11_11.8.1), so probably we can remove the patch soon.

**Pull request merged**
