### PR TITLE
Remove ogre=1.12 builds

### PR DESCRIPTION
**Pull request by traversaro**
These builds never worked (see https://github.com/conda-forge/gazebo-feedstock/issues/88) and now that ROS2 RViz is using its own vendored ogre=1.12, there is no reason to keep them around, as they can create problems (see https://github.com/RoboStack/ros-noetic/issues/343) and use CI time to build.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
fyi @Tobias-Fischer

**Comment by Tobias-Fischer** [comment]
Lgtm, thanks!

**Pull request merged**
