### PR TITLE
Cleanup pinnings and fix use of ffmpeg dependencies

### PR DESCRIPTION
**Pull request by traversaro**
In particular: 
* Change max_pin to x, as Gazebo minor version  are ABI backward compatible 
* Remove run dependencies for packages that correctly have run_exports 
* Remove explicitly pinning of libsdformat and ignition-common3

This was necessary because the new Gazebo build after https://github.com/conda-forge/gazebo-feedstock/pull/37 caused the Gazebo build again to depend transitively on libuuid on macOS, with all the problems already discussed in https://github.com/conda-forge/libignition-common-feedstock/pull/18 . Example of build failed for this: https://github.com/robotology/robotology-superbuild/pull/544/checks?check_run_id=1467517151 . 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The use of `libignition-common3` 3.7 meant that ffmpeg was brought in as a transitive dependency, and then the linking of Gazebo against ffmpeg was failing for the usual  https://github.com/conda-forge/cmake-feedstock/issues/129 . I updated the `fix_build.patch` to handle also that case.

I also fixed the test on Windows that checked for the existence of `gazebo.dll`, when now that file was renamed in `libgazebo.dll` in https://github.com/osrf/gazebo/pull/2864, and now a proper `gazebo.exe` exists. The fact that those test did not failed in https://github.com/conda-forge/gazebo-feedstock/pull/37 is quite strange.

**Comment by traversaro** [comment]
The additional fix was sufficient on macOS, while it did not worked on Linux, I guess for those subtle differences in linking behaviour between Linux and macOS . Let's look for another strategy.

**Comment by traversaro** [comment]
A more definitive path (switching to just use imported targets) is available in https://github.com/osrf/gazebo/compare/gazebo11...traversaro:patch-5.patch .

**Comment by traversaro** [comment]
> 
> 
> A more definitive path (switching to just use imported targets) is available in https://github.com/traversaro/gazebo/commit/5761f25860353ade33741ea585e9fefa3db88b59.patch .

The improvement of this patch is that now also Windows fails. : ) 
Apparently there is something else that is injecting the need for the swscale.so.5 and the other ffmpeg libraries, see the error: 
~~~
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libswscale.so.5, needed by gazebo/common/libgazebo_common.so.11.3.0, not found (try using -rpath or -rpath-link)
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libavdevice.so.58, needed by gazebo/common/libgazebo_common.so.11.3.0, not found (try using -rpath or -rpath-link)
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libavformat.so.58, needed by gazebo/common/libgazebo_common.so.11.3.0, not found (try using -rpath or -rpath-link)
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libavutil.so.56, needed by gazebo/common/libgazebo_common.so.11.3.0, not found (try using -rpath or -rpath-link)
~~~

Probably the easiest fix is just to workaround https://github.com/conda-forge/cmake-feedstock/issues/129 by adding a `add_link_options(-L"${CMAKE_INSTALL_PREFIX}/lib")` that is a brittle solution but should work even if new dependencies are enabled.

**Comment by traversaro** [comment]
I think I finally understood why we have all this linking problems. The CI sets a reasonable options for the linker in the LDFLAGS environment variable, that is typically read by CMake and put in the [`CMAKE_EXE_LINKER_FLAGS`](https://cmake.org/cmake/help/latest/variable/CMAKE_EXE_LINKER_FLAGS.html) and [`CMAKE_SHARED_LINKER_FLAGS`](https://cmake.org/cmake/help/latest/variable/CMAKE_SHARED_LINKER_FLAGS.html). The problem is that the Gazebo build system overwrites this values in https://github.com/osrf/gazebo/blob/gazebo11/cmake/DefaultCFlags.cmake#L41 .

**Comment by traversaro** [comment]
Finally, indeed the fix in https://github.com/conda-forge/gazebo-feedstock/pull/38/commits/6c5bd6bc6b65f8df0224bc64aa521b8f503efd19 was sufficient to fix the build. I think that after this fix many of the patch https://github.com/conda-forge/gazebo-feedstock/blob/master/recipe/fix_build.patch can be simplified substantially, but probably it make more sense to do it in a future release.

**Comment by Tobias-Fischer** [comment]
Great work @traversaro! A similar issue was haunting me when trying to get `slam-toolbox` to compile: https://github.com/RoboStack/ros-noetic/blob/master/patch/ros-noetic-slam-toolbox.patch

Took me a little while to figure out what to do there, too.

Agreed that the patch can probably be simplified now - I'll create an issue to keep track of this, and assign you if you don't mind.

**Pull request merged**
