### PR TITLE
v11.2

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Skipping Windows as we need a recent version of sdformat which is currently blocked due to https://github.com/conda-forge/libsdformat-feedstock/issues/9

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@seanyen @wolfv should we merge this (assuming it builds) and open an issue to re-enable Windows builds, or wait until we can build Windows again? Win builds currently blocked by https://github.com/conda-forge/libsdformat-feedstock/issues/9

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Just to understand, why it was necessary to manually pin `libsdformat`  to 9.3 when 9.3 is the latest version?

**Comment by Tobias-Fischer** [comment]
There is some weird version conflict going on - investigating at the moment. Mamba would probably help. Pinning it didn't do the trick; will check more in the next few days

**Comment by wolfv** [comment]
I checked with mamba and the problem is:

libsdformat-9.3.0-h4bf3a07_1 requires libignition-math6 >=6.6.0,<6.7.0a0

and

libignition-transport8 pins libignition-math6 6.4.x (>=6.4.0,<6.5.0a0)

We might have been too strict with the pinnings for these packages (@traversaro should we pin to major version? are all 6.x releases binary compatible?).

We could rebuild libignition-transport8 with the newer ignition-math ... More generally we should figure out how we can add these packages to conda-forge so that migrations are triggered for libignition-transport8 whenever libignition-math6 changes... I am afraid the versioning scheme won't make this easy for us, though :(

**Comment by wolfv** [comment]
PS this is the command to find the conflict: 

`CONDA_SUBDIR=win-64 mamba create -n abc123 --dry-run libsdformat=9.3 libignition-transport8`

Before, I checked with mambabuild (need to install `boa` for this command to be available):

`CONDA_SUBDIR=win-64 conda mambabuild recipe/`

**Comment by traversaro** [comment]
> @traversaro should we pin to major version? are all 6.x releases binary compatible?

Yes, and that holds true for all ignition libraries (and sdformat as well) follow semantic versioning for the C++ ABI as well, and they also have automatic ABI checks for all the PRs.

**Comment by wolfv** [comment]
@traversaro so basically we can remove all pinnings since the major version is already in the package name, correct? The dependency 

`libignition-common3 >=3.4.0,<3.5.0a0`

can safely be converted to 

`libignition-common3`

right?

**Comment by wolfv** [comment]
@traversaro this would be the repodata diff (for linux):

PR Here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/98

```diff
linux-64::gazebo-11.0.0-h2bf7b13_5.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3",
+    "libignition-fuel-tools4",
+    "libignition-transport8",
linux-64::gazebo-11.0.0-h2bf7b13_6.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3",
+    "libignition-fuel-tools4",
+    "libignition-transport8",
linux-64::gazebo-11.0.0-h2bf7b13_7.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-fuel-tools4 >=4.0.0,<4.1.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3",
+    "libignition-fuel-tools4",
+    "libignition-transport8",
linux-64::gazebo-11.0.0-h32bde7a_11.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3",
+    "libignition-fuel-tools4",
+    "libignition-transport8",
linux-64::gazebo-11.0.0-h398b6f7_8.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3",
+    "libignition-fuel-tools4",
+    "libignition-transport8",
linux-64::gazebo-11.0.0-h398b6f7_9.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3",
+    "libignition-fuel-tools4",
+    "libignition-transport8",
linux-64::gazebo-11.0.0-h83d8fc8_11.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3",
+    "libignition-fuel-tools4",
+    "libignition-transport8",
linux-64::gazebo-11.0.0-hb54441d_10.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-fuel-tools4 >=4.1.0,<4.2.0a0",
-    "libignition-transport8 >=8.0.0,<8.1.0a0",
+    "libignition-common3",
+    "libignition-fuel-tools4",
+    "libignition-transport8",
linux-64::gazebo-11.1.0-h1c9e8e2_0.tar.bz2
-    "libignition-common3 >=3.6.1,<3.7.0a0",
-    "libignition-fuel-tools4 >=4.2.1,<4.3.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3",
+    "libignition-fuel-tools4",
+    "libignition-transport8",
linux-64::gazebo-11.1.0-hfe1d10a_0.tar.bz2
-    "libignition-common3 >=3.6.1,<3.7.0a0",
-    "libignition-fuel-tools4 >=4.2.1,<4.3.0a0",
-    "libignition-transport8 >=8.1.0,<8.2.0a0",
+    "libignition-common3",
+    "libignition-fuel-tools4",
+    "libignition-transport8",
linux-64::libignition-common-3.3.0-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.2.0,<6.3.0a0",
+    "libignition-math6",
linux-64::libignition-common3-3.3.0-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libignition-common3-3.4.0-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libignition-common3-3.4.0-hf10cc52_1.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libignition-common3-3.4.0-hf10cc52_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libignition-common3-3.4.0-hf10cc52_3.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libignition-common3-3.5.0-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libignition-common3-3.5.0-hf10cc52_1.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libignition-common3-3.5.0-hf10cc52_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libignition-common3-3.6.1-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libignition-common3-3.7.0-hf10cc52_0.tar.bz2
-    "libignition-math6 >=6.6.0,<6.7.0a0",
+    "libignition-math6",
linux-64::libignition-fuel-tools-4.0.0-h693f921_0.tar.bz2
-    "libignition-common3 >=3.3.0,<3.4.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3",
+    "libignition-msgs5",
linux-64::libignition-fuel-tools4-4.0.0-h693f921_0.tar.bz2
-    "libignition-common3 >=3.3.0,<3.4.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3",
+    "libignition-msgs5",
linux-64::libignition-fuel-tools4-4.0.0-h693f921_1.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3",
+    "libignition-msgs5",
linux-64::libignition-fuel-tools4-4.0.0-h693f921_2.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3",
+    "libignition-msgs5",
linux-64::libignition-fuel-tools4-4.1.0-h693f921_0.tar.bz2
-    "libignition-common3 >=3.4.0,<3.5.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3",
+    "libignition-msgs5",
linux-64::libignition-fuel-tools4-4.1.0-hc81f71f_1.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-common3",
+    "libignition-msgs5",
linux-64::libignition-fuel-tools4-4.1.0-hc81f71f_2.tar.bz2
-    "libignition-common3 >=3.5.0,<3.6.0a0",
-    "libignition-msgs5 >=5.3.0,<5.4.0a0",
+    "libignition-common3",
+    "libignition-msgs5",
linux-64::libignition-fuel-tools4-4.2.1-hc81f71f_0.tar.bz2
-    "libignition-common3 >=3.6.1,<3.7.0a0",
-    "libignition-msgs5 >=5.3.0,<5.4.0a0",
+    "libignition-common3",
+    "libignition-msgs5",
linux-64::libignition-math4-4.0.0-he1b5a44_0.tar.bz2
-    "libignition-cmake0 >=0.6.1,<0.7.0a0",
+    "libignition-cmake0",
linux-64::libignition-math6-6.2.0-he1b5a44_0.tar.bz2
-    "libignition-cmake2 >=2.1.1,<2.2.0a0",
+    "libignition-cmake2",
linux-64::libignition-math6-6.4.0-he1b5a44_0.tar.bz2
-    "libignition-cmake2 >=2.1.1,<2.2.0a0",
+    "libignition-cmake2",
linux-64::libignition-math6-6.4.0-he1b5a44_1.tar.bz2
-    "libignition-cmake2 >=2.1.1,<2.2.0a0",
+    "libignition-cmake2",
linux-64::libignition-math6-6.4.0-he1b5a44_2.tar.bz2
-    "libignition-cmake2 >=2.5.0,<2.6.0a0",
+    "libignition-cmake2",
linux-64::libignition-math6-6.6.0-he1b5a44_0.tar.bz2
-    "libignition-cmake2 >=2.5.0,<2.6.0a0",
+    "libignition-cmake2",
linux-64::libignition-msgs1-1.0.0-h17a9b65_1.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
-    "libignition-tools >=0.2.0,<0.3.0a0",
+    "libignition-math4",
+    "libignition-tools",
linux-64::libignition-msgs1-1.0.0-h7adf49d_0.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
-    "libignition-tools >=0.2.0,<0.3.0a0",
+    "libignition-math4",
+    "libignition-tools",
linux-64::libignition-msgs1-1.0.0-hfcd16c1_2.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
-    "libignition-tools >=0.2.0,<0.3.0a0",
+    "libignition-math4",
+    "libignition-tools",
linux-64::libignition-msgs5-5.1.0-hab906e7_2.tar.bz2
-    "libignition-math6 >=6.4",
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
+    "libignition-math6",
linux-64::libignition-msgs5-5.1.0-hab906e7_4.tar.bz2
-    "libignition-math6 >=6.4",
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
+    "libignition-math6",
linux-64::libignition-msgs5-5.1.0-hfcd16c1_0.tar.bz2
-    "libignition-math6 >=6.4",
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
+    "libignition-math6",
linux-64::libignition-msgs5-5.1.0-hfcd16c1_1.tar.bz2
-    "libignition-math6 >=6.4",
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
+    "libignition-math6",
linux-64::libignition-msgs5-5.3.0-ha44d269_1.tar.bz2
-    "libignition-math6 >=6.4",
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
+    "libignition-math6",
linux-64::libignition-msgs5-5.3.0-hab906e7_0.tar.bz2
-    "libignition-math6 >=6.4",
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
+    "libignition-math6",
linux-64::libignition-msgs6-6.0.0-ha44d269_0.tar.bz2
-    "libignition-math6 >=6.4",
-    "libignition-math6 >=6.6.0,<6.7.0a0",
+    "libignition-math6",
+    "libignition-math6",
linux-64::libignition-transport4-4.0.0-h0822b3d_0.tar.bz2
-    "libignition-msgs1 >=1.0.0,<1.1.0a0",
+    "libignition-msgs1",
linux-64::libignition-transport4-4.0.0-h91258d1_2.tar.bz2
-    "libignition-msgs1 >=1.0.0,<1.1.0a0",
+    "libignition-msgs1",
linux-64::libignition-transport4-4.0.0-hd0f77ff_1.tar.bz2
-    "libignition-msgs1 >=1.0.0,<1.1.0a0",
+    "libignition-msgs1",
linux-64::libignition-transport8-8.0.0-h1322465_2.tar.bz2
-    "libignition-msgs5 >=5.3.0,<5.4.0a0",
+    "libignition-msgs5",
linux-64::libignition-transport8-8.0.0-h85f8c2c_1.tar.bz2
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-msgs5",
linux-64::libignition-transport8-8.0.0-h91258d1_0.tar.bz2
-    "libignition-msgs5 >=5.1.0,<5.2.0a0",
+    "libignition-msgs5",
linux-64::libignition-transport8-8.1.0-h1322465_0.tar.bz2
-    "libignition-msgs5 >=5.3.0,<5.4.0a0",
+    "libignition-msgs5",
linux-64::libsdformat-6.2.0-h16e5e93_1.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
+    "libignition-math4",
linux-64::libsdformat-6.2.0-h16e5e93_2.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
+    "libignition-math4",
linux-64::libsdformat-6.2.0-h16e5e93_3.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
+    "libignition-math4",
linux-64::libsdformat-6.2.0-h16e5e93_4.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
+    "libignition-math4",
linux-64::libsdformat-6.2.0-h40aee75_0.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
+    "libignition-math4",
linux-64::libsdformat-6.2.0-h6dc373c_0.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
+    "libignition-math4",
linux-64::libsdformat-6.2.0-had2f1a9_1.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
+    "libignition-math4",
linux-64::libsdformat-6.2.0-had2f1a9_2.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
+    "libignition-math4",
linux-64::libsdformat-6.2.0-had2f1a9_3.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
+    "libignition-math4",
linux-64::libsdformat-6.2.0-had2f1a9_4.tar.bz2
-    "libignition-math4 >=4.0.0,<4.1.0a0",
+    "libignition-math4",
linux-64::libsdformat-9.1.0-h16e5e93_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.1.0-h16e5e93_1.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.1.0-h40aee75_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.1.0-h40aee75_3.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.1.0-h6dc373c_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.1.0-h6dc373c_3.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.1.0-had2f1a9_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.1.0-had2f1a9_1.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.2.0-h11736c9_1.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.2.0-h26a1ef3_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.2.0-h40aee75_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.2.0-h623d0aa_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.2.0-h6dc373c_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.2.0-h833df14_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.2.0-hbca141e_1.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.2.0-hd597c45_2.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.3.0-h26a1ef3_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.3.0-h32b47e2_1.tar.bz2
-    "libignition-math6 >=6.6.0,<6.7.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.3.0-h623d0aa_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.3.0-h833df14_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.3.0-had1f909_1.tar.bz2
-    "libignition-math6 >=6.6.0,<6.7.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.3.0-hb5a3e86_1.tar.bz2
-    "libignition-math6 >=6.6.0,<6.7.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.3.0-hd597c45_0.tar.bz2
-    "libignition-math6 >=6.4.0,<6.5.0a0",
+    "libignition-math6",
linux-64::libsdformat-9.3.0-hf7a5c58_1.tar.bz2
-    "libignition-math6 >=6.6.0,<6.7.0a0",
+    "libignition-math6",
```

Does that look good to you?

**Comment by traversaro** [comment]
> 
> 
> @traversaro so basically we can remove all pinnings since the major version is already in the package name, correct? The dependency
> 
> `libignition-common3 >=3.4.0,<3.5.0a0`
> 
> can safely be converted to
> 
> `libignition-common3`
> 
> right?

I am not sure, I guess that if something was compiled against libignition-common3 3.4.0, it could use some symbols that they were introduced only in that release, so I think that the constraint >=3.4.0 needs to be there. The other constraint would be < 4.0.0, but that is probably not necessary if we package each major release as a different package. fyi @j-rivero

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please restart ci

**Comment by Tobias-Fischer** [comment]
Weird things happening now. `ligignition-common3` requires `dlfcn-win32` which in turn requires `glib`. However:
```
CONDA_SUBDIR=win-64 mamba create -n abc123 --dry-run libsdformat=9.3 glib

Encountered problems while solving.
Problem: nothing provides m2w64-gcc-libs needed by libffi-3.2.1-ha925a31_1007
```

Any ideas @conda-forge/gazebo @wolfv? Seems like a bigger issue than ignition-stuff now (the ignition issues should have been resolved by my recent PRs)

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please restart ci

**Comment by wolfv** [comment]
@Tobias-Fischer indeed, I saw this too, but I thought the `msys2` channel would be enabled by default ... maybe we need to ask on gitter about this.

**Comment by traversaro** [comment]
> `dlfcn-win32` which in turn requires `glib`.

Just to understand, where does this dependency come from? I do not see in https://github.com/conda-forge/dlfcn-win32-feedstock/blob/master/recipe/meta.yaml any dependency on glib, and dlfcn-win32 by itself does not depend even implicitly on glib (upstream we have CI that tests dlfcn-win32 on both MSVC and mingw-64).

**Comment by wolfv** [comment]
yeah i am debugging this, now, too. let me see

**Comment by wolfv** [comment]
I think this is just a bug in mamba where it prints a non-great conflict message. When trying this: `CONDA_SUBDIR=win-64 mamba create -n abc123 --dry-run libignition-common3 libsdformat=9.3` then it still fails with 

```
Problem: package libsdformat-9.3.0-hbeba28f_1 requires libignition-math6 >=6.6.0,<6.7.0a0, but none of the providers can be installed
```

I think that will be fixed with the repodata patch. Let me get to it :)

**Comment by wolfv** [comment]
(because afaik, we didn't backport the changes to old branches, right?)

**Comment by traversaro** [comment]
> 
> 
> (because afaik, we didn't backport the changes to old branches, right?)

In the case of ignition-math6 the major version 6 is the one handled by the master branch, but probably we merged that after we did the last sdformat rebuild.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please restart ci

**Comment by Tobias-Fischer** [comment]
See https://github.com/conda-forge/libignition-common-feedstock/pull/14 for the pin on libignition-common - once that's merged we should be good to remove the pin again

**Comment by wolfv** [comment]
Nice!

**Pull request merged**
