### PR TITLE
OSX build

### LINKED ISSUE #16: OSX build
Needs builds for 

- [x] https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/6
- [x] https://github.com/conda-forge/libignition-common-feedstock/pull/8
- [x] https://github.com/conda-forge/libsdformat-feedstock/pull/8

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Fix #16

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @wolfv,
This fails because of some odd dependency issues re `libconsole_bridge`. You recently updated this package (https://github.com/conda-forge/console_bridge-feedstock/pull/6) - any idea how to get everything back in sync?

Thanks!

**Comment by Tobias-Fischer** [comment]
(this also blocks #17)

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please restart ci

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Amazing, this works. This is ready to be merged :rocket: @conda-forge/gazebo

**Comment by wolfv** [comment]
Awesome, congrats!

**Pull request merged**
