### PR TITLE
Enable dartsim dependency on Windows

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/conda-forge/gazebo-feedstock/issues/138 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Failure is:
~~~
[586/1134] Building CXX object gazebo\physics\CMakeFiles\gazebo_physics.dir\dart\DARTCollision.cc.obj
FAILED: gazebo/physics/CMakeFiles/gazebo_physics.dir/dart/DARTCollision.cc.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x64\cl.exe  /nologo /TP -DABSL_CONSUME_DLL -DBOOST_ALL_DYN_LINK -DBOOST_IOSTREAMS_NO_LIB=1 -DBUILDING_DLL -DBUILDING_DLL_GZ_PHYSICS -DDART_ACTIVE_LOG_LEVEL=2 -DDART_HAVE_spdlog=1 -DFMT_HEADER_ONLY=1 -DFMT_SHARED -DIGN_PROFILER_ENABLE=0 -DLIBBULLET_VERSION=0.0 -DNOMINMAX -DNOUSER -DPROTOBUF_USE_DLLS -DSPDLOG_FMT_EXTERNAL -DTINYXML2_IMPORT -DWIN32_LEAN_AND_MEAN -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_USE_MATH_DEFINES -DdIDEDOUBLE -Dgazebo_physics_EXPORTS -I%SRC_DIR%\test\gtest\include -I%SRC_DIR% -I%SRC_DIR%\build -I%PREFIX%\Library\include\libusb-1.0 -external:I%SRC_DIR%\deps\opende\include -external:I%PREFIX%\Library\include -external:I%PREFIX%\Library\include\ignition\msgs5 -external:I%PREFIX%\Library\include\ignition\math6 -external:I%PREFIX%\Library\include\ignition\transport8 -external:I%PREFIX%\Library\include\ignition\common3 -external:I%PREFIX%\Library\include\ignition\fuel_tools4 -external:I%PREFIX%\Library\include\OGRE\RTShaderSystem -external:I%PREFIX%\Library\include\OGRE -external:I%PREFIX%\Library\include\OGRE\Terrain -external:I%PREFIX%\Library\include\OGRE\Paging -external:I%PREFIX%\Library\include\OGRE\Overlay -external:I%PREFIX%\Library\include\sdformat-9.8 -external:I%PREFIX%\Library\include\sdformat-9.8\sdf\.. -external:I%PREFIX%\Library\include\ignition\cmake2 -external:I%PREFIX%\Library\include\eigen3 -external:I%PREFIX%\Library\include\bullet -external:I%PREFIX%\Library\CMake\..\include -external:W0 /DWIN32 /D_WINDOWS /W3 /GR /EHsc       /wd4005 /wd4068 /wd4244 /wd4251 /wd4267 /wd4275 /wd4996 /EHsc /MD /O2 /Ob2 /DNDEBUG -std:c++17   /EHsc -I"D:/bld/gazebo_1693385550269/_h_env/Library/include" /Zc:__cplusplus /permissive- /Zc:strictStrings- /Zc:externC- /showIncludes /Fogazebo\physics\CMakeFiles\gazebo_physics.dir\dart\DARTCollision.cc.obj /Fdgazebo\physics\CMakeFiles\gazebo_physics.dir\ /FS -c %SRC_DIR%\gazebo\physics\dart\DARTCollision.cc
%PREFIX%\Library\include\eigen3\Eigen\src/Core/Transpose.h(301): fatal error C1060: compiler is out of heap space
[587/1134] Building CXX object gazebo\physics\CMakeFiles\gazebo_physics.dir\dart\DARTBoxShape.cc.obj
FAILED: gazebo/physics/CMakeFiles/gazebo_physics.dir/dart/DARTBoxShape.cc.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x64\cl.exe  /nologo /TP -DABSL_CONSUME_DLL -DBOOST_ALL_DYN_LINK -DBOOST_IOSTREAMS_NO_LIB=1 -DBUILDING_DLL -DBUILDING_DLL_GZ_PHYSICS -DDART_ACTIVE_LOG_LEVEL=2 -DDART_HAVE_spdlog=1 -DFMT_HEADER_ONLY=1 -DFMT_SHARED -DIGN_PROFILER_ENABLE=0 -DLIBBULLET_VERSION=0.0 -DNOMINMAX -DNOUSER -DPROTOBUF_USE_DLLS -DSPDLOG_FMT_EXTERNAL -DTINYXML2_IMPORT -DWIN32_LEAN_AND_MEAN -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_USE_MATH_DEFINES -DdIDEDOUBLE -Dgazebo_physics_EXPORTS -I%SRC_DIR%\test\gtest\include -I%SRC_DIR% -I%SRC_DIR%\build -I%PREFIX%\Library\include\libusb-1.0 -external:I%SRC_DIR%\deps\opende\include -external:I%PREFIX%\Library\include -external:I%PREFIX%\Library\include\ignition\msgs5 -external:I%PREFIX%\Library\include\ignition\math6 -external:I%PREFIX%\Library\include\ignition\transport8 -external:I%PREFIX%\Library\include\ignition\common3 -external:I%PREFIX%\Library\include\ignition\fuel_tools4 -external:I%PREFIX%\Library\include\OGRE\RTShaderSystem -external:I%PREFIX%\Library\include\OGRE -external:I%PREFIX%\Library\include\OGRE\Terrain -external:I%PREFIX%\Library\include\OGRE\Paging -external:I%PREFIX%\Library\include\OGRE\Overlay -external:I%PREFIX%\Library\include\sdformat-9.8 -external:I%PREFIX%\Library\include\sdformat-9.8\sdf\.. -external:I%PREFIX%\Library\include\ignition\cmake2 -external:I%PREFIX%\Library\include\eigen3 -external:I%PREFIX%\Library\include\bullet -external:I%PREFIX%\Library\CMake\..\include -external:W0 /DWIN32 /D_WINDOWS /W3 /GR /EHsc       /wd4005 /wd4068 /wd4244 /wd4251 /wd4267 /wd4275 /wd4996 /EHsc /MD /O2 /Ob2 /DNDEBUG -std:c++17   /EHsc -I"D:/bld/gazebo_1693385550269/_h_env/Library/include" /Zc:__cplusplus /permissive- /Zc:strictStrings- /Zc:externC- /showIncludes /Fogazebo\physics\CMakeFiles\gazebo_physics.dir\dart\DARTBoxShape.cc.obj /Fdgazebo\physics\CMakeFiles\gazebo_physics.dir\ /FS -c %SRC_DIR%\gazebo\physics\dart\DARTBoxShape.cc
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\include\utility(184): fatal error C1060: compiler is out of heap space
[588/1134] Building CXX object gazebo\physics\CMakeFiles\gazebo_physics.dir\dart\DARTBallJoint.cc.obj
FAILED: gazebo/physics/CMakeFiles/gazebo_physics.dir/dart/DARTBallJoint.cc.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x64\cl.exe  /nologo /TP -DABSL_CONSUME_DLL -DBOOST_ALL_DYN_LINK -DBOOST_IOSTREAMS_NO_LIB=1 -DBUILDING_DLL -DBUILDING_DLL_GZ_PHYSICS -DDART_ACTIVE_LOG_LEVEL=2 -DDART_HAVE_spdlog=1 -DFMT_HEADER_ONLY=1 -DFMT_SHARED -DIGN_PROFILER_ENABLE=0 -DLIBBULLET_VERSION=0.0 -DNOMINMAX -DNOUSER -DPROTOBUF_USE_DLLS -DSPDLOG_FMT_EXTERNAL -DTINYXML2_IMPORT -DWIN32_LEAN_AND_MEAN -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_USE_MATH_DEFINES -DdIDEDOUBLE -Dgazebo_physics_EXPORTS -I%SRC_DIR%\test\gtest\include -I%SRC_DIR% -I%SRC_DIR%\build -I%PREFIX%\Library\include\libusb-1.0 -external:I%SRC_DIR%\deps\opende\include -external:I%PREFIX%\Library\include -external:I%PREFIX%\Library\include\ignition\msgs5 -external:I%PREFIX%\Library\include\ignition\math6 -external:I%PREFIX%\Library\include\ignition\transport8 -external:I%PREFIX%\Library\include\ignition\common3 -external:I%PREFIX%\Library\include\ignition\fuel_tools4 -external:I%PREFIX%\Library\include\OGRE\RTShaderSystem -external:I%PREFIX%\Library\include\OGRE -external:I%PREFIX%\Library\include\OGRE\Terrain -external:I%PREFIX%\Library\include\OGRE\Paging -external:I%PREFIX%\Library\include\OGRE\Overlay -external:I%PREFIX%\Library\include\sdformat-9.8 -external:I%PREFIX%\Library\include\sdformat-9.8\sdf\.. -external:I%PREFIX%\Library\include\ignition\cmake2 -external:I%PREFIX%\Library\include\eigen3 -external:I%PREFIX%\Library\include\bullet -external:I%PREFIX%\Library\CMake\..\include -external:W0 /DWIN32 /D_WINDOWS /W3 /GR /EHsc       /wd4005 /wd4068 /wd4244 /wd4251 /wd4267 /wd4275 /wd4996 /EHsc /MD /O2 /Ob2 /DNDEBUG -std:c++17   /EHsc -I"D:/bld/gazebo_1693385550269/_h_env/Library/include" /Zc:__cplusplus /permissive- /Zc:strictStrings- /Zc:externC- /showIncludes /Fogazebo\physics\CMakeFiles\gazebo_physics.dir\dart\DARTBallJoint.cc.obj /Fdgazebo\physics\CMakeFiles\gazebo_physics.dir\ /FS -c %SRC_DIR%\gazebo\physics\dart\DARTBallJoint.cc
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\include\xtree(1286): fatal error C1060: compiler is out of heap space
ninja: build stopped: subcommand failed.
~~~

**Comment by Tobias-Fischer** [comment]
Looks like this is ready to go?

```
-- Found DART: D:/bld/gazebo_1693404026579/_h_env/Library/include (Required is at least version "6.6") found components: collision-bullet collision-ode utils-urdf dart 
-- Looking for DART - found
```

**Comment by traversaro** [comment]
Yes!

**Pull request merged**
