### PR TITLE
Simplify fix_build.patch

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

As discussed in https://github.com/conda-forge/gazebo-feedstock/issues/39, thanks to https://github.com/conda-forge/gazebo-feedstock/pull/38 it should be now possible to drastically simplify the fix_build.patch .

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Seems like the cinttypes patch is still required. Probably something we should patch upstream.

**Comment by Tobias-Fischer** [comment]
Looking good now, thanks a lot. Could you please bump the build number and re-render just for good measure?

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> 
> 
> Looking good now, thanks a lot. Could you please bump the build number and re-render just for good measure?

Done!

**Comment by Tobias-Fischer** [comment]
I guess it's fine to re-render next time. Thanks for the PR!

**Pull request merged**
