### PR TITLE
Enable aarch64 build via cross-compilation on Azure

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Warnings are appearning that you need `libignition-msgs5`

> 2022-06-05T17:10:12.0503502Z WARNING (gazebo,lib/gazebo-11/plugins/libContainPlugin.so): .. but ['libignition-msgs5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)


Not sure where this warning is coming from:
> 2022-06-05T17:10:02.3578256Z WARNING (gazebo,lib/gazebo-11/plugins/libSimpleTrackedVehiclePlugin.so): $RPATH/libTrackedVehiclePlugin.so not found in packages, sysroot(s) nor the missing_dso_whitelist.

Also `assimp`
> 2022-06-05T17:10:01.5186421Z WARNING (gazebo,lib/gazebo-11/plugins/libGravityCompensationPlugin.so): Needed DSO lib/libassimp.so.5 found in ['assimp']
> 2022-06-05T17:10:01.5188034Z WARNING (gazebo,lib/gazebo-11/plugins/libGravityCompensationPlugin.so): .. but ['assimp'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)


> 2022-06-05T17:09:53.3830696Z WARNING (gazebo,lib/libgazebo_physics.so.11.11.0): Needed DSO lib/libignition-msgs5.so.5 found in ['libignition-msgs5']
2022-06-05T17:09:53.3832391Z WARNING (gazebo,lib/libgazebo_physics.so.11.11.0): .. but ['libignition-msgs5'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
2022-06-05T17:09:53.4074642Z    INFO (gazebo,lib/libgazebo_physics.so.11.11.0): Needed DSO lib/libignition-math6.so.6 found in conda-forge::libignition-math6-6.11.0-py310h3f2b827_1
2022-06-05T17:09:53.4299207Z    INFO (gazebo,lib/libgazebo_physics.so.11.11.0): Needed DSO lib/libboost_regex.so.1.74.0 found in conda-forge::boost-cpp-1.74.0-h6cacc03_7
2022-06-05T17:09:53.4535851Z    INFO (gazebo,lib/libgazebo_physics.so.11.11.0): Needed DSO lib/libode.so.0.16.2 found in conda-forge::libode-0.16.2-hd8f1fbe_10
2022-06-05T17:09:53.4580584Z    INFO (gazebo,lib/libgazebo_physics.so.11.11.0): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libpthread.so.0 found in CDT/compiler package conda-forge::sysroot_linux-64-2.17-h4a8ded7_13
2022-06-05T17:09:53.4819037Z WARNING (gazebo,lib/libgazebo_physics.so.11.11.0): Needed DSO lib/liburdfdom_world.so.3.0 found in ['urdfdom']
2022-06-05T17:09:53.4820686Z WARNING (gazebo,lib/libgazebo_physics.so.11.11.0): .. but ['urdfdom'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
2022-06-05T17:09:53.5062094Z    INFO (gazebo,lib/libgazebo_physics.so.11.11.0): Needed DSO lib/libdart.so.6.12 found in conda-forge::dartsim-6.12.1-h8aa081f_5
2022-06-05T17:09:53.5313528Z WARNING (gazebo,lib/libgazebo_physics.so.11.11.0): Needed DSO lib/libassimp.so.5 found in ['assimp']
2022-06-05T17:09:53.5315218Z WARNING (gazebo,lib/libgazebo_physics.so.11.11.0): .. but ['assimp'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
2022-06-05T17:09:53.5559605Z    INFO (gazebo,lib/libgazebo_physics.so.11.11.0): Needed DSO lib/libSimTKmath.so.3.7 found in conda-forge::simbody-3.7-h64f3f5a_3
2022-06-05T17:09:53.5812380Z    INFO (gazebo,lib/libgazebo_physics.so.11.11.0): Needed DSO lib/libSimTKcommon.so.3.7 found in conda-forge::simbody-3.7-h64f3f5a_3
2022-06-05T17:09:53.6062928Z WARNING (gazebo,lib/libgazebo_physics.so.11.11.0): Needed DSO lib/libopenblas.so.0 found in ['libopenblas']
2022-06-05T17:09:53.6064716Z WARNING (gazebo,lib/libgazebo_physics.so.11.11.0): .. but ['libopenblas'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)


My "hunch" is that it is related to the openblas warning. Maybe you can cleanup the other ones, then ping somebody with more experience.

**Comment by traversaro** [comment]
Hi @hmaarrfk, thanks for pointing to the warnings. However, the warnings appear also on the `linux64` (`amd64`) build, so they are not strictly related to the aarch64 build. So if it is ok for you I would open a separate issue for those warnings, without blocking this PR.

@Tobias-Fischer what do you think of this PR? I am double checking to avoid conflicts with the aarch64 build of Gazebo in robostack.

**Comment by Tobias-Fischer** [comment]
Happy for it to be merged unless @hmaarrfk feels strongly about the warnings.

**Comment by hmaarrfk** [comment]
I don't. I'm just trying to help where I can

**Comment by traversaro** [comment]
> I don't. I'm just trying to help where I can

And that is super-welcome! We can continue the discussion in https://github.com/conda-forge/gazebo-feedstock/issues/136 .

**Pull request merged**
