### PR TITLE
Ffmpeg 4.4

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@hmaarrfk Any reason for removing the qt pin? Unfortunatly it is required for https://github.com/conda-forge/gazebo-feedstock/issues/119 .

**Comment by hmaarrfk** [comment]
I was not aware of this issue. I was mostly trying to resolve the environment, which seems tricky with that old build which may not have update pinnings

**Comment by hmaarrfk** [comment]
I had to open this by hand since i made a mistake in the previous migrator which tried to upgrade windows to FFMPEG 4.4 which does not exist. 

We are trying to build ffmpeg 5.0 for windows, but no ETA.

**Comment by hmaarrfk** [comment]
Feel free to push and adjust this as needed for your usecase.

**Comment by traversaro** [comment]
I think that the problem is that we are missing a ffmpeg 4.4 build for libignition-common3, i.e. blocked by https://github.com/conda-forge/libignition-common-feedstock/pull/46 .

**Review by traversaro — APPROVED** [review]

**Comment by hmaarrfk** [comment]
what do you think was happening? why do you think it will succeed now?

**Comment by Tobias-Fischer** [comment]
https://github.com/conda-forge/libignition-common-feedstock/pull/46 was merged in, and hence this PR should succeed now (that's my understanding)

I'm confused with the ffmpeg 4.4 migration though - was it stopped in the remainder of conda-forge, and are we now out of sync? Should we revert the migrations that have happened?

**Comment by hmaarrfk** [comment]
i probably jumped the gun closing the ffmpeg 4.4 migration. typically when we are at the last layer of feedstocks, I don't see the need to wait. For this one, we I guess this got triggered when `main` was migrated, but not when `v3` was migrated.

In my mind the migrations create this kind of inconsistent state:
* New feedstocks need to build with quite old packages, to get what htey want.
* Existing feedstocks are getting rebuilt with new pinnings.

For feedstocks with many dependencies, such as this one, it sometimes becomes impossible to move forward because many migrations are happening at the same time. This is why I closed out FFMPEG 4.4 when this was the only feedstock remaining (with a few other ones too)

**Pull request merged**
