### PR TITLE
V9.x

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Supersedes #22

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @wolfv @traversaro any idea why the Linux build cannot find -lboost_thread? Haven't seen this before ..
Can fix the OSX issue next week some time.

**Comment by traversaro** [comment]
> 
> 
> Hi @wolfv @traversaro any idea why the Linux build cannot find -lboost_thread? Haven't seen this before ..
> Can fix the OSX issue next week some time.

I am probably missing something, but the build error on Linux seems to be tbb-related, I could not find any error in `boost_thread` in the log: 
~~~
[196/1102] Linking CXX shared library gazebo/common/libgazebo_common.so.9.15.0
FAILED: gazebo/common/libgazebo_common.so.9.15.0 
: && $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -fPIC -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/gazebo-9.15.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix   -Wall -Wextra -Wno-long-long -Wno-unused-value -Wfloat-equal -Wshadow -Wswitch-default -Wmissing-include-dirs -pedantic -fvisibility=hidden -fvisibility-inlines-hidden   -s -O3 -DNDEBUG -mssse3 -msse3 -mfpmath=sse -msse -msse2   -shared -Wl,-soname,libgazebo_common.so.9 -o gazebo/common/libgazebo_common.so.9.15.0 gazebo/common/CMakeFiles/gazebo_common.dir/Animation.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Assert.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/AudioDecoder.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Battery.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Base64.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/BVHLoader.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/ColladaExporter.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/ColladaLoader.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Color.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/CommonIface.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Console.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Dem.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Event.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Events.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Exception.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/HeightmapData.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Image.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/ImageHeightmap.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/KeyEvent.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/KeyFrame.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Material.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/MaterialDensity.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Mesh.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/MeshExporter.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/MeshLoader.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/MeshManager.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/ModelDatabase.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/MouseEvent.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/OBJLoader.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/PID.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/SemanticVersion.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/SkeletonAnimation.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Skeleton.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/SphericalCoordinates.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/STLLoader.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/SystemPaths.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/SVGLoader.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Time.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Timer.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/URI.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Video.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/VideoEncoder.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/ffmpeg_inc.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Profiler.cc.o gazebo/common/CMakeFiles/gazebo_common.dir/Remotery/lib/Remotery.c.o gazebo/common/CMakeFiles/gazebo_common.dir/RemoteryProfilerImpl.cc.o -L$SRC_DIR/build/test -Wl,-rpath,$SRC_DIR/build/test:  $BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr/lib/libdl.so  $PREFIX/lib/libboost_thread.so  -lpthread  $PREFIX/lib/libboost_system.so  $PREFIX/lib/libboost_filesystem.so  $PREFIX/lib/libboost_program_options.so  $PREFIX/lib/libboost_regex.so  $PREFIX/lib/libboost_iostreams.so  $PREFIX/lib/libboost_date_time.so  $PREFIX/lib/libboost_chrono.so  $PREFIX/lib/libboost_atomic.so  $PREFIX/lib/libfreeimage.so  $PREFIX/lib/libtinyxml.so  $PREFIX/lib/libcurl.so  $PREFIX/lib/libtar.so  -ltbb  $PREFIX/lib/libsdformat.so  $PREFIX/lib/libignition-math4.so.4.0.0  -lpthread  -lrt && :
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -ltbb
~~~

**Comment by traversaro** [comment]
The log contains this message on tbb:
~~~
2020-10-30T07:31:01.7667456Z -- Checking for module 'tbb'
2020-10-30T07:31:01.7864969Z --   No package 'tbb' found
2020-10-30T07:31:01.7869855Z -- TBB not found, attempting to detect manually
~~~

So it means that we are taking this branch: https://github.com/osrf/gazebo/blob/gazebo9_9.15.0/cmake/SearchForStuff.cmake#L309, as the tbb package on conda-forge does not provide a .pc file, and then something is going wrong (not sure what do to be honest, the code seems to be fine). However, as the TBB conda-forge package provide a CMake config file we could backport the patch https://github.com/osrf/gazebo/commit/183122dc0d6f96d030c48b1a09d3d46d962fad45 to Gazebo 9, so that the CMake config and its imported target is used, avoid all the problems related to manual search.

**Comment by wolfv** [comment]
sounds like a great idea, backporting the tbb find fix.

**Comment by Tobias-Fischer** [comment]
Ha, https://github.com/conda-forge/gazebo-feedstock/pull/33/commits/64b6d68ca0ddb6fd5bd6ffee94bb8f8288d34a23 must have fixed boost.

Thanks a lot for linking to the TBB patch @traversaro - let's see if it works :)

**Comment by traversaro** [comment]
> Ha, [64b6d68](https://github.com/conda-forge/gazebo-feedstock/commit/64b6d68ca0ddb6fd5bd6ffee94bb8f8288d34a23) must have fixed boost.

Ah yes, the direct inclusion of `Find-script` instead of just calling them implicitly with `find_package` is one of the most mysterious way of gazebo build system, I guess they work quite by chance.

**Comment by Tobias-Fischer** [comment]
@wolfv @traversaro - do you think it makes sense to push this on Windows as well? Not sure if it's needed, we'll soon have Gazebo11 on Win. I'm also not sure what would be required to get it to work ..

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> 
> 
> @wolfv @traversaro - do you think it makes sense to push this on Windows as well? Not sure if it's needed, we'll soon have Gazebo11 on Win. I'm also not sure what would be required to get it to work ..

Back in time when I was working in getting Gazebo10 in vcpkg, the amount of patches was not negligible, and then I submitted all the fixes just for Gazebo11 as no one show interest in backporting them to Gazebo9 . If I remember correctly anyhow @seanyen has a Gazebo 9 build for Windows, so perhaps most of those patches I needed for vcpkg where for vcpkg-specific problem (i.e. ogre 1.12 and no support for pkg-config).  However, personally my focus is just to get Gazebo11 on Windows (as that is what we already ship in https://github.com/robotology/robotology-superbuild-dependencies-vcpkg), and if your focus is ROS Noetic, then I far as I understand the target Gazebo there is 11 (see https://github.com/robotology/robotology-superbuild-dependencies-vcpkg), so I think it is ok to drop Windows support for Gazebo 9 and just support Windows on Gazebo 11.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Great, thanks for letting us know @traversaro. Skipping the Windows build in this case which makes it easier.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Do you think we can merge this @seanyen @wolfv @traversaro?

**Review by traversaro — APPROVED** [review]

**Comment by wolfv** [comment]
thanks!

**Pull request merged**
