### PR TITLE
Enable OSX ARM64

### PR DESCRIPTION
**Pull request by traversaro**
This also features a change similar to https://github.com/conda-forge/libignition-msgs1-feedstock/pull/41 to support cross-compilation (by backporting https://github.com/osrf/gazebo/pull/3190). The main difference is that here we do not build all the build gazebo project, but just the necessary binary `gazebomsgs_out`.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Blocked by https://github.com/conda-forge/qwt-feedstock/pull/33 .

**Comment by Tobias-Fischer** [comment]
Latest error: 

CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   FREEIMAGE_RUNS (advanced)

**Review by Tobias-Fischer — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Awesome! Let's automerge?

**Comment by traversaro** [comment]
> Awesome! Let's automerge?

Done!

**Pull request merged**
