### PR TITLE
Add aarch64

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@traversaro - should I add you as maintainer while a PR is open? :)

**Comment by Tobias-Fischer** [comment]
Ahh gosh, libprotobuf giving us issues on all platforms. Any idea what's going wrong there?
```
FAILED: gazebo/msgs/gazebomsgs_out 
: && $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/gazebo-11.3.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix       -Wall -Wextra -Wno-long-long -Wno-unused-value -Wfloat-equal -Wshadow -Wswitch-default -Wmissing-include-dirs -pedantic -fvisibility=hidden -fvisibility-inlines-hidden -std=c++17  -s -O3 -DNDEBUG -mssse3 -msse3 -mfpmath=sse -msse -msse2  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib gazebo/msgs/CMakeFiles/gazebomsgs_out.dir/generator/GazeboGenerator.cc.o gazebo/msgs/CMakeFiles/gazebomsgs_out.dir/generator/gazebo_generator.cc.o  -o gazebo/msgs/gazebomsgs_out -L$SRC_DIR/build/test -Wl,-rpath,$SRC_DIR/build/test  $PREFIX/lib/libprotobuf.so  $PREFIX/lib/libprotoc.so  -lpthread && :
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: gazebo/msgs/CMakeFiles/gazebomsgs_out.dir/generator/GazeboGenerator.cc.o: in function `google::protobuf::compiler::cpp::GazeboGenerator::Generate(google::protobuf::FileDescriptor const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const':
GazeboGenerator.cc:(.text._ZNK6google8protobuf8compiler3cpp15GazeboGenerator8GenerateEPKNS0_14FileDescriptorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS1_16GeneratorContextEPSC_+0x45c): undefined reference to `google::protobuf::io::Printer::Print(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: GazeboGenerator.cc:(.text._ZNK6google8protobuf8compiler3cpp15GazeboGenerator8GenerateEPKNS0_14FileDescriptorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS1_16GeneratorContextEPSC_+0x4b6): undefined reference to `google::protobuf::io::Printer::Print(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: GazeboGenerator.cc:(.text._ZNK6google8protobuf8compiler3cpp15GazeboGenerator8GenerateEPKNS0_14FileDescriptorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS1_16GeneratorContextEPSC_+0x510): undefined reference to `google::protobuf::io::Printer::Print(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: GazeboGenerator.cc:(.text._ZNK6google8protobuf8compiler3cpp15GazeboGenerator8GenerateEPKNS0_14FileDescriptorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS1_16GeneratorContextEPSC_+0x56a): undefined reference to `google::protobuf::io::Printer::Print(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: GazeboGenerator.cc:(.text._ZNK6google8protobuf8compiler3cpp15GazeboGenerator8GenerateEPKNS0_14FileDescriptorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS1_16GeneratorContextEPSC_+0x5c4): undefined reference to `google::protobuf::io::Printer::Print(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: gazebo/msgs/CMakeFiles/gazebomsgs_out.dir/generator/GazeboGenerator.cc.o:GazeboGenerator.cc:(.text._ZNK6google8protobuf8compiler3cpp15GazeboGenerator8GenerateEPKNS0_14FileDescriptorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS1_16GeneratorContextEPSC_+0x6af): more undefined references to `google::protobuf::io::Printer::Print(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: gazebo/msgs/CMakeFiles/gazebomsgs_out.dir/generator/GazeboGenerator.cc.o:(.data.rel.ro._ZTVN6google8protobuf8compiler3cpp15GazeboGeneratorE[_ZTVN6google8protobuf8compiler3cpp15GazeboGeneratorE]+0x28): undefined reference to `google::protobuf::compiler::CodeGenerator::GenerateAll(std::vector<google::protobuf::FileDescriptor const*, std::allocator<google::protobuf::FileDescriptor const*> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const'
collect2: error: ld returned 1 exit status
```

**Comment by traversaro** [comment]
> 
> 
> @traversaro - should I add you as maintainer while a PR is open? :)

Sure!

**Comment by traversaro** [comment]
For some reason protobuf 3.5 is installed, together with libprotobuf 3.15 . Not sure why.

**Comment by traversaro** [comment]
Not sure if it plays a role, but I guess that protobuf should be an explicit build dependency, not just libprotobuf.

**Comment by traversaro** [comment]
> 
> 
> Not sure if it plays a role, but I guess that protobuf should be an explicit build dependency, not just libprotobuf.

Sorry, my bad, this does not make sense, protobuf only contains the python protobuf bindings. Probably protobuf 3.5.1 instead also contained the C++ library, and if both protobuf 3.5 and libprotobuf 3.15 are installed, the old C++ library contained in protobuf 3.5 is found instead of the one contained in libprotobuf.

**Comment by Tobias-Fischer** [comment]
Needs https://github.com/conda-forge/qwt-feedstock/pull/26 first

**Comment by Tobias-Fischer** [comment]
@traversaro: seems like adding protobuf to host deps fixed the problem, though.

**Comment by traversaro** [comment]
> 
> 
> @traversaro: seems like adding protobuf to host deps fixed the problem, though.

Interesting, probably some arcane dependency installation rule intervene in this case. However, we depend on protobuf in all other ignition recipe, so if we need to start investigating removing the protobuf dependency (leaving only libprotobuf) we can start from simple recipes such as ignition-msgs .

**Comment by Tobias-Fischer** [comment]
Right. I suggest for this PR to add protobuf for now, and then remove the protobuf dependency in the ignition recipes one by one?

**Comment by traversaro** [comment]
> Right. I suggest for this PR to add protobuf for now, and then remove the protobuf dependency in the ignition recipes one by one?

This make sense!

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please restart ci

**Comment by wolfv** [comment]
hm, looks like issues with the build timeout on drone... 

Longer term we coudl think about installing the azure worker on the sponsored ARM machine... as I proposed on the Qt Feedstock. Would mean that we need to figure out how to give permissions only to certain feedstocks.

**Comment by Tobias-Fischer** [comment]
Yes, an Azure worker would be a great long term solution, agreed! In the short term, shall I build it manually on the conda forge server and then upload it?

**Comment by Tobias-Fischer** [comment]
Hi @wolfv - quick ping re a manual build?

**Comment by Tobias-Fischer** [comment]
Superseded by #64

**Pull request closed without merging**
