### PR TITLE
Enable graphviz also on Windows

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@Tobias-Fischer I am out of the lab right now, but just FYI to fix the graphviz on Windows problem we need (I think) to do what is mentioned in https://github.com/gazebosim/gazebo-classic/pull/3270#issuecomment-1294221743 .

**Comment by Tobias-Fischer** [comment]
Thanks @traversaro! I tried that in https://github.com/conda-forge/gazebo-feedstock/pull/154/commits/6b67d7f4c97e8a615455180775a11adab0ce9040 but it didn't do the job. I now have the feeling that the FindGraphviz.cmake needs to be patched, too - maybe we can use the ycm/yarp one?

**Comment by traversaro** [comment]
> Thanks @traversaro! I tried that in [6b67d7f](https://github.com/conda-forge/gazebo-feedstock/commit/6b67d7f4c97e8a615455180775a11adab0ce9040) but it didn't do the job. I now have the feeling that the FindGraphviz.cmake needs to be patched, too - maybe we can use the ycm/yarp one?

I think we just need the logic in https://github.com/robotology/ycm/pull/414/files#diff-b74b735f51ee92142633fdbbc03ff177cef1af251b02c4acb6842e239b1106e8R98 in the `FindGraphviz.cmake` 's from Gazebo. We can also avoid the option-related logic as in conda-forge we can assume that the Windows build will be shared.

**Comment by Tobias-Fischer** [comment]
Still no luck. I’ll wait till you are back in the lab ..

**Comment by Tobias-Fischer** [comment]
Good catch, silly me …

**Pull request merged**
