### PR TITLE
Add aarch take 2

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
I can't recall why we need to add protobuf (that is the Python package) as a dependency, it was for some wrong resolving of dependencies, right?

**Comment by Tobias-Fischer** [comment]
Yeah, there is a very old version of protobuf around that doesn't have proper run_exports, which gets pulled in if we don't specify protobuf as a dependency explicitly.

We decided that it's best to remove all protobuf dependency from the ignition feedstocks, but start bottom-up.

**Comment by Tobias-Fischer** [comment]
I just uploaded a new version based on the latest commit in master to https://anaconda.org/RoboStack/gazebo - @wolfv @traversaro what do you reckon, should we upload it to the conda-forge channel?

**Comment by traversaro** [comment]
Ok for me, but how it works? Should we merge this PR in any case?

**Comment by traversaro** [comment]
> Yeah, there is a very old version of protobuf around that doesn't have proper run_exports, which gets pulled in if we don't specify protobuf as a dependency explicitly.
> 
> We decided that it's best to remove all protobuf dependency from the ignition feedstocks, but start bottom-up.

Possibily related issue: https://github.com/conda-forge/libignition-msgs1-feedstock/issues/30 .

**Comment by Tobias-Fischer** [comment]
Yes, we'd merge anyhow, then rebuild manually for new versions and upload manually to the conda forge channel - I don't think we've got write access, but presumably @wolfv would.

**Pull request closed without merging**
