### PR TITLE
Add fix for #148

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/conda-forge/gazebo-feedstock/issues/148 by backporting https://github.com/gazebosim/gazebo-classic/pull/3269 .

Other changes that landed in this PR for some reason or another:
* workaround for https://github.com/conda-forge/conda-forge.github.io/issues/1823
* fix hash of the package after rename from `osrf/gazebo` to `gazebosim/gazebo-classic`.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
As a first step, in https://github.com/conda-forge/gazebo-feedstock/pull/152/commits/b48c9aabb6edd25990ac23afe954786877c5aeba I enabled a subset of Gazebo testsuite that is running fine and that is not working until https://github.com/conda-forge/gazebo-feedstock/issues/148 is fixed.

**Comment by traversaro** [comment]
Ok, the test are failing as expected on `osx-64` . Now time for the workaround, we try to stick to clang 11 for the time being.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Locally I was building with clang11 and macOS SDK 12.3 and it was working (i.e. `INTEGRATION_transport_msg_count` testing was passing), but for some reason on the CI even with this combination it is not working.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
I am not sure whether this could be the source of the issue, but from the last successful build on main, there are some warnings:
```
WARNING (gazebo,lib/gazebo-11/plugins/libWheelTrackedVehiclePlugin.dylib): $RPATH/libTrackedVehiclePlugin.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?


WARNING (gazebo,lib/gazebo-11/plugins/libSimpleTrackedVehiclePlugin.dylib): $RPATH/libTrackedVehiclePlugin.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
```

Also, gazebo looks for a python interpreter, but we don't list python in the dependencies. Could this be an issue?

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> I am not sure whether this could be the source of the issue, but from the last successful build on main, there are some warnings:
> 
> ```
> WARNING (gazebo,lib/gazebo-11/plugins/libWheelTrackedVehiclePlugin.dylib): $RPATH/libTrackedVehiclePlugin.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.
> .. is this binary repackaging?
> 
> 
> WARNING (gazebo,lib/gazebo-11/plugins/libSimpleTrackedVehiclePlugin.dylib): $RPATH/libTrackedVehiclePlugin.dylib not found in packages, sysroot(s) nor the missing_dso_whitelist.
> .. is this binary repackaging?
> ```
> 
> Also, gazebo looks for a python interpreter, but we don't list python in the dependencies. Could this be an issue?

Sorry, I just read this. I do not think this is related.

**Comment by traversaro** [comment]
The patch https://github.com/conda-forge/gazebo-feedstock/pull/152/commits/ebeea0fe50498bcbf6a4246595921ee94340f7a4 fix the tests on my local system, but breaks the tests even on Linux. Probably it is the case to actually have instantiation of the Singleton template in every compilation unit, and just have one, I will try to prepare a fix on that line.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by azeey** [comment]
Explicit instantiation may not work reliably. From my tests, it only seems to work in Debug mode. As discussed in https://github.com/gazebosim/gz-common/pull/451, I think the best thing to do is to create an `Instance` member function in each class that inherits from `Singleton<T>` that simply does `return SingletonT<T>::Instance()` where `T` is the desired type.

**Comment by traversaro** [comment]
> Explicit instantiation may not work reliably. From my tests, it only seems to work in Debug mode. As discussed in [gazebosim/gz-common#451](https://github.com/gazebosim/gz-common/pull/451), I think the best thing to do is to create an `Instance` member function in each class that inherits from `Singleton<T>` that simply does `return SingletonT<T>::Instance()` where `T` is the desired type. Edit: This member function has to be defined in the `.cc` file of the class to avoid the creation of weak symbols due to inlining.

Nice trick, thanks! On Gazebo Classic we have the additional burden of the ABI stability, and unfortunatly you can't override a static member function (see https://stackoverflow.com/questions/34222703/how-to-override-static-method-of-template-class-in-derived-class). An alternative that could work and is ABI-compatible is to define a method with `Instance`-like name (such as `GetUniqueInstance`), use that one instead of `Instance`, and mark `Instance` as deprecated to make sure that downstream code does not use it.

**Comment by traversaro** [comment]
> > Explicit instantiation may not work reliably. From my tests, it only seems to work in Debug mode. As discussed in [gazebosim/gz-common#451](https://github.com/gazebosim/gz-common/pull/451), I think the best thing to do is to create an `Instance` member function in each class that inherits from `Singleton<T>` that simply does `return SingletonT<T>::Instance()` where `T` is the desired type. Edit: This member function has to be defined in the `.cc` file of the class to avoid the creation of weak symbols due to inlining.
> 
> Nice trick, thanks! On Gazebo Classic we have the additional burden of the ABI stability, and unfortunatly you can't override a static member function (see https://stackoverflow.com/questions/34222703/how-to-override-static-method-of-template-class-in-derived-class). An alternative that could work and is ABI-compatible is to define a method with `Instance`-like name (such as `GetUniqueInstance`), use that one instead of `Instance`, and mark `Instance` as deprecated to make sure that downstream code does not use it.

Actually I just realized that also in those PRs you are not removing the inheritance, so probably I am missing something as there you are doing overriding of a static method.

**Comment by traversaro** [comment]
> Actually I just realized that also in those PRs you are not removing the inheritance, so probably I am missing something as there you are doing overriding of a static method.

I think I got it, basically the static methods can coexist, but if you cast the method that inherits from SingletonT to (SingletonT*) and call `Instance()`, you will still get the `SingletonT` one. Anyhow, I do not think this is a big problem in practice.

**Comment by traversaro** [comment]
Even with this fix, the test is not passing on the CI. At this point, I start to believe that the reason why the test is hanging in the CI is not related to the reason why the test is hanging on our local machines.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Let's enable the load of artifacts so I can try it locally indipendently from the CI.

**Comment by azeey** [comment]
> I think I got it, basically the static methods can coexist, but if you cast the method that inherits from SingletonT to (SingletonT*) and call Instance(), you will still get the SingletonT one. Anyhow, I do not think this is a big problem in practice.

Yes, in order to avoid ABI breaks, we resorted to shadowing the static function in `SingletonT`. I doubt we have any uses where the `Instance` is called via the base class, so I also don't think it's an issue.

**Comment by traversaro** [comment]
I just tested locally on osx-arm64, and gazebo works even if the test does not pass on the CI. Probably the test is stuck for some other reason.

**Comment by traversaro** [comment]
I also updated the sha256 that changed due to the repo rename and organization change.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
So should we trigger automerge?

**Comment by traversaro** [comment]
> So should we trigger automerge?

I want first to check on osx-64, it should not take long.

**Comment by traversaro** [comment]
Just as a last check for the CI test, I fixed the issue for all Singletons (see https://github.com/gazebosim/gazebo-classic/pull/3269), and I re-launched the CI with the test.

**Comment by traversaro** [comment]
> > So should we trigger automerge?
> 
> I want first to check on osx-64, it should not take long.

In the end we tested with @lrapetti that encountered this problem today totally by chance, and the last build was working fine.

**Comment by traversaro** [comment]
> Just as a last check for the CI test, I fixed the issue for all Singletons (see [gazebosim/gazebo-classic#3269](https://github.com/gazebosim/gazebo-classic/pull/3269)), and I re-launched the CI with the test.

Nope, the test are hanging for some other reasons.

**Pull request merged**
